# -*- coding: utf-8 -*-
"""Breakout.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1siMskgLr8GcaZ_yuGvxdIpw2tfqm0oqX

## Import Dependencies
"""

!pip install stable_baselines3[extra]
!pip install gym[all]

import gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.env_util import make_atari_env
import os

"""## Test Environment"""

# http://www.atarimania.com/roms/Roms.rar

!pip install patool
import patoolib
patoolib.extract_archive("/content/Roms.rar", outdir="/content/")

!python -m atari_py.import_roms /content/ROMS

environment_name = 'Breakout-v0'
env = gym.make(environment_name)

env.reset()

env.action_space

env.observation_space

episodes=5
for episode in range(1,episodes+1):
  obs = env.reset()
  done = False
  score = 0
  while not done:
    #env.render()
    action = env.action_space.sample()
    obs,reward,done,info = env.step(action)
    score+=reward
  print('Episode:{} Score:{}'.format(episode,score))
#env.close()

"""## Vectorise Environment and Train Model"""

# Vectorise envt. rather than using a single envt.

env = make_atari_env('Breakout-v0',n_envs=4,seed=0)
env = VecFrameStack(env, n_stack=4)

env.reset()

#env.render()
#env.close()

log_path = os.path.join('Training','Logs')
model = A2C('CnnPolicy',env,verbose=1,tensorboard_log=log_path)
#MlpPolicy is good for tabular data
#CnnPolicy is useful for images as we are training on image based data here

model.learn(total_timesteps=100000)

"""## Save and Reload Model"""

a2c_path=os.path.join('Training','Saved Models','A2C_Breakout_Model')
model.save(a2c_path)

del model

model = A2C.load(a2c_path,env)

"""## Evaluate and Test"""

env = make_atari_env('Breakout-v0',n_envs=1,seed=0)
env = VecFrameStack(env,n_stack=4)

from stable_baselines3.common.evaluation import evaluate_policy # to test how our model is performing
# Ideally, model should get a score>4
evaluate_policy(model,env,n_eval_episodes=10,render=False)

